export const SET_LOCATION = "SET_LOCATION";
export const SET_NAME = "SET_NAME";
export const SET_FIRES = "SET_FIRES"
export const SET_USER_LOCATIONS="SET_USER_LOCATIONS";
export const SET_LAST_ALERT = "SET_LAST_ALERT"
export const SET_VIEWPORT = "SET_VIEWPORT";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_COORDS = "SET_COORDS";
export const SET_ALL_COORDS = "SET_ALL_COORDS"
